import { none } from 'fp-ts/Option';

import { KeyFrame } from './reducer/keyboard';

//macキーボードにしよう
//up-downキー
export const initialKeyFrame: KeyFrame[] = [
  {
    position: { x: 0, y: 0 },
    size: '1.5U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 1, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 2, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 3, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 4, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 5, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 6, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 7, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 8, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 9, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 10, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 11, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 12, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 13, y: 0 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 0, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 1, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 2, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 3, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 4, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 5, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 6, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 7, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 8, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 9, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 10, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 11, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 12, y: 1 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 13, y: 1 },
    size: '1.5U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 0, y: 2 },
    size: '1.25U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 1, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 2, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 3, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 4, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 5, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 6, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 7, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 8, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 9, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 10, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 11, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 12, y: 2 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 0, y: 3 },
    size: '1.75U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 1, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 2, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 3, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 4, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 5, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 6, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 7, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 8, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 9, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 10, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 11, y: 3 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 12, y: 3 },
    size: '1.75U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 0, y: 4 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 1, y: 4 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 2, y: 4 },
    size: '1.25U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 3, y: 4 },
    size: '1.25U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 4, y: 4 },
    size: '3.5U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 5, y: 4 },
    size: '1.25U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 6, y: 4 },
    size: '1.25U',
    isPut: false,
    keycap: none,
  },
  {
    position: { x: 7, y: 4 },
    size: '1U',
    isPut: false,
    keycap: none,
  },
  //up-downキーボード
  {
    position: { x: 8, y: 4 },
    size: '3U',
    isPut: false,
    keycap: none,
  },
];
